# Generated by Django 5.2.10 on 2026-02-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
