# Generated by Django 5.2.10 on 2026-02-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_userprofile_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
