# Generated by Django 5.2.10 on 2026-02-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('hls_playlist', models.FileField(upload_to='videos/hls/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='video_app.video')),
            ],
        ),
    ]
