# Generated by Django 5.2.10 on 2026-02-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_videoresolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
