# Generated by Django 5.2.10 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_remove_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='VideoResolution',
        ),
    ]
