# Generated by Django 5.2.10 on 2026-03-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_remove_video_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
    ]
