# Generated by Django 5.2.10 on 2026-03-07 15:23

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_remove_video_thumbnail_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to=video_app.models.video_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to=video_app.models.thumbnail_upload_path),
        ),
    ]
